### PR TITLE
feat: github release integration

### PR DESCRIPTION
**Pull request by pi0**
Usage: 

```sh
changelogen gh release <versions...>
```

(more usage is updated in the docs)

### CODE REVIEW

**Comment by Atinux** [comment]
Beautiful 💯 

I still like the idea of open GitHub to create/update the release so you don't even need to ask user for a GitHub token

**Comment by pi0** [comment]
Agreed it is not always convinient to require a token! 

We have two ideas: 

- Show link to open GitHub create release page with prefilled contents if there is no token (not in this PR)
- A GitHub action that syncs the release (https://github.com/unjs/changelogen/issues/32) which can built on the same sync feature and auto-provided github token in the action

**Comment by Atinux** [comment]
> Show link to open GitHub create release page with prefilled contents if there is no token (not in this PR)

Release it open the link in browser directly but I like the idea of showing the url :)

GitHub action is a nice idea as well but will need documenting

**Comment by pi0** [comment]
Thanks for the feedback and ideas! I have added a fallback mechanism for manual release:

image

(auto opening in browser is possible but cannot use `open` package today because of downstream bundling issues. we have a fixed version in c12 which have to eventually extract to citty)

**Pull request merged**
