### PR TITLE
feat!: support different repository providers

### PR DESCRIPTION
**Pull request by dnldsht**
Introduced support for different git hosts and format references accordingly

Checking the specs for the [repository](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#repository) field in package.json you can define different providers (github, gitlab, ...) so I've added the support for that and formatted the references (commit, pull-request, issue, compare) accordingly.

I've introduced a breaking change removing the `github` prop from the config, I can restore it and make it compatible with the new feature.

I'm really bad at naming :) I've used `host` I'm open for better name

I've also fixed 2 minor bugs:
- broken ungh link
- issue reference for github `ssue` -> `issue`

### CODE REVIEW

**Comment by dnldsht** [comment]
@pi0 any comment about the PR?

**Comment by pi0** [comment]
Hi dear @dnldsht sorry this was stalled. Do you mind to rebase your pull request?

**Comment by dnldsht** [comment]
Yess I will sync my PR

**Review by pi0 — APPROVED** [review]
Thanks!

**Pull request merged**
